# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory:  "/01-birthday reminder"
    schedule:
      interval: "daily"
      
      - package-ecosystem: "npm" # See documentation for possible values
    directory:  "/02-tours"
    schedule:
      interval: "daily"
      
    - package-ecosystem: "npm" # See documentation for possible values
    directory:   "/03-reviews"
    schedule:
      interval: "daily"
      
    - package-ecosystem: "npm" # See documentation for possible values
    directory:   "/04-accordion"
    schedule:
      interval: "daily"
      
       - package-ecosystem: "npm" # See documentation for possible values
    directory:  "/05-menu"
    schedule:
      interval: "daily"
      
       - package-ecosystem: "npm" # See documentation for possible values
    directory:   "/06-tabs"
    schedule:
      interval: "daily"
      
       - package-ecosystem: "npm" # See documentation for possible values
    directory:  "/07-slider"
    schedule:
      interval: "daily"
      
       - package-ecosystem: "npm" # See documentation for possible values
    directory:   "/08-lorem ipsum generator"
    schedule:
      interval: "daily"
      
      - package-ecosystem: "npm" # See documentation for possible values
    directory:  "/09- color generator"
    schedule:
      interval: "daily"
      
      - package-ecosystem: "npm" # See documentation for possible values
    directory: "/10-grocery-bud"
    schedule:
      interval: "daily"
  
     
    
