# Basic dependabot.yml file with
# minimum configuration for two package managers


updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: {
      "/01-birthday reminder",
      "/02-tours",
      "/03-reviews",
      "/04-accordion",
      "/05-menu",
      "/06-tabs",
      "/07-slider",
      "/08-lorem ipsum generator",
      "/09- color generator",
      "/10-grocery-bud",
    }
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"